apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kite-pvc
  namespace: apps
  labels:
    app: kite
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
