# handlers file for ssh_hardening 
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart ssh socket
  ansible.builtin.systemd:
    name: ssh.socket
    state: restarted
    daemon_reload: true
