apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: apps
spec:
  interval: 10m
  chart:
    spec:
      chart: headlamp
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
  # https://github.com/headlamp-k8s/headlamp/blob/main/charts/headlamp/values.yaml
  values:
