apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    nodeSelector:
      nvidia.com/gpu: "true"

    # Use CDI strategy for device discovery
    deviceListStrategy: cdi

    # Fail on init error set to false for graceful handling
    failOnInitError: false

    # Resource limits for the plugin
    resources:
      requests:
        cpu: 10m
        memory: 15Mi
      limits:
        memory: 50Mi

    # Tolerations for GPU nodes
    tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

    # Priority class for system critical workloads
    priorityClassName: system-node-critical
