apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- node-exporter-dashboard.yaml
- prometheus-rules.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: homelab-monitoring
    app.kubernetes.io/component: alerts

namespace: monitoring