apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: apps
  labels:
    app: stirling-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: stirlingtools/stirling-pdf:2.14.2
          ports:
            - containerPort: 8080
          env:
            - name: SECURITY_ENABLELOGIN
              value: "true"
            - name: SYSTEM_DEFAULTLOCALE
              value: "en-GB"
            - name: UI_APPNAME
              value: "Stirling-PDF"
            - name: SECURITY_INITIALLOGIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stirling-pdf-credentials
                  key: username
            - name: SECURITY_INITIALLOGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stirling-pdf-credentials
                  key: password
          volumeMounts:
            - name: stirling-pdf-data
              mountPath: /configs
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 3Gi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
      volumes:
        - name: stirling-pdf-data
          persistentVolumeClaim:
            claimName: stirling-pdf-pvc
