apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-pvc
  namespace: apps
  labels:
    app: stirling-pdf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
