apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 10m
  releaseName: n8n
  chartRef:
    kind: OCIRepository
    name: n8n
  values:
    image:
      tag: 1.74.1
    nodeSelector:
      kubernetes.io/arch: amd64
