apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 10m
  chart:
    spec:
      chart: n8n
      version: 0.25.2
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: apps
  values:
