apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: n8n
  namespace: apps
spec:
  chart: n8n
  version: 0.25.0
  sourceRef:
    kind: HelmRepository
    name: n8n
  interval: 10m