apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 1h
  chart:
    spec:
      chart: oci://8gears.container-registry.com/library/n8n
      version: "1.0.10"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # n8n configuration
    n8n:
      # Database configuration - PostgreSQL
      database:
        type: postgresdb
        postgresdb:
          host: k3s-worker1
          port: 5432
          database: postgres
          schema: n8n
          user: 
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: username
          password:
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
      
      # Webhook URL
      webhookUrl: https://n8n.yuandrk.net
      
      # Encryption key (should be set for production)
      encryptionKey: "n8n-production-encryption-key-32chars"
      
    # Deployment configuration
    deployment:
      image:
        repository: n8nio/n8n
        pullPolicy: IfNotPresent
        # Don't use latest tag, let the chart decide the version
      
      # Resources
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    
    # Service configuration
    service:
      type: ClusterIP
      port: 80
      targetPort: 5678
    
    # Ingress configuration
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - host: n8n.yuandrk.net
          paths:
            - /
    
    # Persistence for n8n data
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 5Gi
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000