apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 10m
  chart:
    spec:
      chart: n8n
      version: 0.25.0
      sourceRef:
        kind: OCIRepository
        name: n8n
        namespace: apps
  values:
