apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: n8n
  namespace: apps
spec:
  interval: 10m
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    tag: "0.25.0"
