apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 30m
  chart:
    spec:
      chart: jenkins
      version: "5.7.16"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      # Jenkins admin user configuration
      admin:
        existingSecret: "jenkins-credentials"
        userKey: admin_user
        passwordKey: admin_password
      
      # Resource configuration
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "2000m"
          memory: "4096Mi"
      
      # Java options for better performance
      javaOpts: "-Xms512m -Xmx2048m"
      
      # Jenkins plugins to install - none for initial deployment
      installPlugins: []
      
      # Service account configuration
      serviceAccount:
        create: true
        name: jenkins
      
      # Security context
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true
      
      # Service configuration
      serviceType: ClusterIP
      
      # Ingress configuration for Traefik
      ingress:
        enabled: true
        ingressClassName: traefik
        hostName: jenkins.yuandrk.net
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
      
      # Disable Jenkins setup wizard (we'll use configuration as code)
      JCasC:
        defaultConfig: true
        configScripts:
          welcome-message: |
            jenkins:
              systemMessage: |
                Welcome to your Jenkins homelab instance!
                This instance is managed via Configuration as Code.
    
    # Persistent storage configuration
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "local-path"
    
    # Agent configuration
    agent:
      enabled: true
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "2048Mi"
    
    # Note: backup configuration removed as it's deprecated in v5.7.16
    
    # RBAC configuration
    rbac:
      create: true
      readSecrets: true
  
  valuesFrom:
    - kind: Secret
      name: jenkins-credentials
      valuesKey: admin_user
      targetPath: controller.admin.username
    - kind: Secret
      name: jenkins-credentials
      valuesKey: admin_password
      targetPath: controller.admin.password