apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m0s
  timeout: 5m0s
  chart:
    spec:
      chart: authentik
      version: "2025.8.1"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: authentik-credentials
      valuesKey: secret-key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-credentials
      valuesKey: postgresql-password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-credentials
      valuesKey: admin-password
      targetPath: authentik.bootstrap_password
  values:
    authentik:
      error_reporting:
        enabled: false
      env:
        AUTHENTIK_HOST: "https://auth.yuandrk.net"
        AUTHENTIK_HOST_BROWSER: "https://auth.yuandrk.net"
      postgresql:
        host: "k3s-worker1"
        port: 5432
        name: authentik
        user: authentik
      secret_key: ""
      bootstrap_password: ""
    postgresql:
      enabled: false
    redis:
      enabled: true
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - auth.yuandrk.net
        tls:
          - hosts:
              - auth.yuandrk.net
            secretName: authentik-tls