apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2025.6"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    authentik:
      secret_key: "placeholder"
      log_level: info
      error_reporting:
        enabled: true
      postgresql:
        password: "placeholder"
    
    server:
      nodeSelector:
        kubernetes.io/arch: arm64
      env:
        - name: AUTHENTIK_WEB__TRUSTED_PROXIES
          value: "*"
        - name: AUTHENTIK_WEB__CSRF_TRUSTED_ORIGINS
          value: "https://auth.yuandrk.net"
        - name: AUTHENTIK_WEB__USE_X_FORWARDED_PROTO
          value: "true"
        - name: AUTHENTIK_DISABLE_CSRF
          value: "true"
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - auth.yuandrk.net
    
    worker:
      nodeSelector:
        kubernetes.io/arch: arm64
    
    postgresql:
      enabled: true
      auth:
        password: "placeholder"
      primary:
        nodeSelector:
          kubernetes.io/arch: arm64
    
    redis:
      enabled: true
      auth:
        enabled: false
      master:
        nodeSelector:
          kubernetes.io/arch: arm64
  
  valuesFrom:
    - kind: Secret
      name: authentik-credentials
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-credentials  
      valuesKey: postgres_password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-credentials  
      valuesKey: postgres_password
      targetPath: postgresql.auth.password