apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2024.8.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    authentik:
      secret_key: "placeholder"
      error_reporting:
        enabled: true
      postgresql:
        password: "placeholder"
    
    server:
      nodeSelector:
        kubernetes.io/arch: arm64
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: auth.yuandrk.net
            paths:
              - path: /
                pathType: Prefix
    
    worker:
      nodeSelector:
        kubernetes.io/arch: arm64
    
    postgresql:
      enabled: true
      auth:
        password: "placeholder"
      primary:
        nodeSelector:
          kubernetes.io/arch: arm64
    
    redis:
      enabled: true
      auth:
        enabled: false
      master:
        nodeSelector:
          kubernetes.io/arch: arm64
  
  valuesFrom:
    - kind: Secret
      name: authentik-credentials
      valuesKey: secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-credentials  
      valuesKey: postgres_password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-credentials  
      valuesKey: postgres_password
      targetPath: postgresql.auth.password