apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "*" 
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: infra
      interval: 12h
  values: 
    installCRDs: true