apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: headlamp
      version: ">=0.21.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: kube-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  targetNamespace: kube-system
  values:
    image:
      tag: "v0.26.0"

    # Init container to install Flux plugin
    initContainers:
      - name: flux-plugin
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        command:
          - sh
          - -c
          - "cp -r /plugins/* /build/"
        volumeMounts:
          - name: plugins
            mountPath: /build

    # Volume for plugins (using emptyDir for simplicity)
    volumes:
      - name: plugins
        emptyDir: {}

    # Mount plugins volume to main container
    volumeMounts:
      - name: plugins
        mountPath: /headlamp/plugins

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Ingress configuration
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - host: headlamp.yuandrk.net
          paths:
            - path: /
              type: ImplementationSpecific

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Enable plugins
    config:
      pluginsDir: "/headlamp/plugins"

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 100
      runAsGroup: 101