apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: kube-system
type: Opaque
stringData:
    clientSecret: ENC[AES256_GCM,data:bTf24RKq9g39L6iEcaaAUrot9IwAar7y2/4NaKchSFXtkZgxMpF2PjFu+bA3Vb+W5Mw2/EQg8n5dWd67LZa75Ek1Q5X7h2hjazpnjODaCiM4oxk0gvhITyL8EL2iEFz6i1YNIHnzJCkij13C+HT+dTw3MeOQSYsbwrOBRN4ufDk=,iv:5AoknOC+cWp/sZ1TsKfn1RqgXcF6GB3PzzcCcCWI1UY=,tag:12VM2CYe0EjPSVar8Brfjg==,type:str]
sops:
    age:
        - recipient: age1hruxjkg7m9sgjwlf6xvz74cy8l8g8ye0p800uja87w6fhz5qs5yqa2y6xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K241RVRwSlFxaCtRblYv
            c055NHhERmMvcmZqU1dxOFZjcG80MUlZcTNFCmMvY3R6OFBTU0paSVZzSnpsV3dr
            a20zVHVtOFVBWkFFdmJvV3ppRzFSVXMKLS0tIG95WHp0TXpYRDM0bTlJSjR1TDlI
            SnJMZk1BNjN5RFEwamUyN01TRVdFbTQKT/g5hg6vOzPCW1XR29s3WCrlcWZOyRUY
            MfTLDbmTbqZOwal9hjSEq0w+YNbqFtuI6ald1YbqJgtgTZe3s+tjiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T14:27:24Z"
    mac: ENC[AES256_GCM,data:1LIfhitBtDCS1tB6K9ig7wxmbGOa2dCFl9SmIsMzB68i3cy5Ojl+iYEj88qWt78r3+XYbnpX7lDvnf0UNyotzj4UdmBIxGkSVhg5D46l+Iork7cVIHt0jWcYLf8D08dkczzO/iBTiv03InElhs9E0ap1QQao3ac2IHKzwrruAt4=,iv:MAHfAez/igR9F3cB0IS5M1CnbR4MW6t3iVVwQFfnVzw=,tag:KLowdjusk2qUIXLSaMfatw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
