apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: storage
  values:
    nfs:
      server: 10.10.0.2
      path: /srv/nfs/immich
    storageClass:
      name: nfs-immich
      defaultClass: false
      allowVolumeExpansion: true
      reclaimPolicy: Retain
      archiveOnDelete: true
      onDelete: retain
      pathPattern: "${.PVC.namespace}/${.PVC.name}"
