apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: storage
spec:
  interval: 1h
  timeout: 3m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
