apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: kube-system
type: Opaque
stringData:
    clientID: ENC[AES256_GCM,data:hjOhdS8h46iQrMLvklW3MFkMIPE=,iv:OHKkIgHQnIEqU8zVeow4T9I+ZCqHVeJze/URyPoazO0=,tag:skk9SIKGy1c7lN3StjnzOw==,type:str]
    clientSecret: ENC[AES256_GCM,data:kyUFc1zOFU73kiZQ9xKR3kMipr5a0S5v20TWQ8KN0q6Wqj6Cql8bmmz2HPhaP/PgLs9I+MAcpz3Eox+YiFITcA==,iv:xIkqruPCCucDNcF4S3vn5jUgfbiCtLpKutMBAj+NLBM=,tag:9C6dyxBx3AXdfqQmtZz+NQ==,type:str]
    issuerURL: ENC[AES256_GCM,data:KRO2ooKbvcEqEzjV7qoGDl4QHGwZzI3oBDx7SlQ5BLsqa4g=,iv:7AjsXGIPbu21ygBFC4ZWQcZmwCZBnlEl5FKVOMXT1yk=,tag:maTUg8LPG4pltkzpgCYDTA==,type:str]
    scopes: ENC[AES256_GCM,data:1DFoPgTq9cIWLW14Yw==,iv:snyTTAUnlJjVSuemI/+fUCEjYUGbw6IdH9ZTXA9SkGk=,tag:48uO5lABik8rdnINbZPlmg==,type:str]
sops:
    age:
        - recipient: age1hruxjkg7m9sgjwlf6xvz74cy8l8g8ye0p800uja87w6fhz5qs5yqa2y6xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dEhmVStnTjFwK1plcWRk
            Mmc1K01BWG1EQzhuSkNzZDdPZ1IzZGRsTkZVClMzY1E3VTg0dW13bjBtbFFZRUJF
            MnZyY1N6QmUrdC9wT3FVeHRZN3dPY2cKLS0tIDlSWXBLS1IxQ3ZNOC9yZ2hLcTFz
            eWJPZzkvdndtZkxjeCtiNVdIS0RiSVEKQ6/ORWzytWq5ESr1TaEhAuik+CSGh18e
            O4DC4cdsx1BBxMy6LN+SmA5fkM3/mZT4Vs2k9WPl8JckE9mUuhk0jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T11:53:07Z"
    mac: ENC[AES256_GCM,data:T9aABBBYdWsy3IF8318AUXGxHw8ZDDT4U31Lf/Mh9WZEiRulza4xAtKw4n4vvedUtBBpEo5lOvuq5dHVTxHS1/VwGC4ZzdXHrzETxBwIzSk6UNp+8FS6cAtWprvQMYPTbOew3msU3mwuJTC151ASIsessBtEq49xLz1ZcPq4c2k=,iv:HmHJvfD4ZGF/jGo6xxMPg066L5WaqOhMJtt/69PHIaY=,tag:+FEDCogd3PizcI0AsFjJ9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
