apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: kube-system
type: Opaque
stringData:
    clientID: ENC[AES256_GCM,data:jNyacO9QYdtMvu144gEeR1GkuVUUAjwYCpQaqLSCP2O5t43lNKDvkw==,iv:A49IjpxGH5AACH50uDRptbO7FgMPLS9sJAe+ZeX6swQ=,tag:Jx3srmhFYlcpgsht0nUkoQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:MS+1zUT8N2CihkgWfqWnMWVlzT72wauAWgyWIYR2Dn6ww8Ps2W6cSnpDjcQOgchwbXirn69v3f1Eu008A9u706hOWq2PaZHNCYpx2fwepm0jFZ23TfzrxaVwZIK/nzVEYIQlacHM+gyj9mJgNKOiegVPT6toFTohdSQlYO04Wyk=,iv:OoSedWYw7JC4jeQgRiBegALe0Dn8eMVY01o3rabQCzE=,tag:37IDLKcEysXIzOtEjRD0pw==,type:str]
    issuerURL: ENC[AES256_GCM,data:5VMpX0YYCgq67nHNX5OGDyC8sx6pd5m4GPdQdzOjZ67FSirh/OI0D5Y0plXOnOSH,iv:Hk+1YJ6NL1sc2hyNniKOMvpYUMZib/Lsmcy2GbKVXb4=,tag:jt04Z3thzGICm3CJCVhRmg==,type:str]
    scopes: ENC[AES256_GCM,data:jghyglcqzeVf7VNYQNq2vKmxZKgGoF6X8e45,iv:xbwHl10GXJKrQoAeeI19eEnd4GOd++aKyK3aWDpCNN0=,tag:ZHcK+/0kqZRjXYyrDzuxyQ==,type:str]
sops:
    age:
        - recipient: age1hruxjkg7m9sgjwlf6xvz74cy8l8g8ye0p800uja87w6fhz5qs5yqa2y6xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd21RMXNOZ1pGcG8yc2F1
            UmdKY2svdi92UTMxY21NbW02YTJ0MHVvQ0FJCmJJb0Q5OXdvMWc2dDM5YUVuM2ND
            MUhyc2l3WDhWT2hGdXlKZzhkYnFzeFEKLS0tIExkcTFncmhjRkFqdHZpK1BjUWhX
            TEUwTHBBN0tiUUJ0Zm4zYkRlbGVRSXMK1dWuGPIQ/wYvfLCurZtTxjyby/uoCFZW
            3Yz3ESQuViGsF1smdAM9tKcI8rq7HL5IEjNIz8hvP8smbaIOsHHTjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T15:14:19Z"
    mac: ENC[AES256_GCM,data:EZki7MtgwjlWcDZWoHe9zy6PM/TOfY7hbS46pwRb0L6tGzorVI4OadijzJObDnwvtCMI6zlrIibbbXdIN9OO60nJ5qy49RjuoEm+Fi0s3WPA9hoOxMf3H5mlqLF49goVxxUKgFrNZAySto+4CryKERslrUrI8Uidn7E0EuvxDHE=,iv:+1tlBv3lBs8VrHSORA8pD3ARkZFZANrJ8eFf2b7Hn3U=,tag:+i+9C8UJ2kkqvHwM8YELJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
