apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: kube-system
type: Opaque
stringData:
    clientID: ENC[AES256_GCM,data:JuPeVy3vEWqjO5XzqLC8a6dSOIotihjRqAhDHW4XrWubPw0OuB7L/A==,iv:iuZnlevmEynXlDGD7hjgnhcjnOvVMgBA5hm1qs4RPng=,tag:Bkon7OeW8SI5VESe0TThuA==,type:str]
    clientSecret: ENC[AES256_GCM,data:KFVE48Sjd8Xh233eKN8mvN5+j/PX9xAtDCam8QNoDqjZR40xwHWz/blnWEa5k6/dxz2UlnbUx2dGQEsb7rs4OagmIYMWvp5c78ddXTiJ/lShdsCG7hHkaeVm32VewruRK04ATPF0rU/u3Qb4t7VIL61ApewRmt83obGUksOaSyU=,iv:GSinuFdLC/YGf6zhgmXf+EviF+jIQlZ8hACgmu9Edw8=,tag:SIsxDJ8KP5JTn215sTbkIw==,type:str]
    issuerURL: ENC[AES256_GCM,data:mt76olIYfkoU9T33x+u/ll2cMUbGOHujXzCJW2PMUtspzDg8EKc65y1zL4r/Zi5z,iv:65XeAx+xCVvkLQi6byilo/nja2vuc0KVEkUzraeSmF8=,tag:2MCR7MlwdGTcZ4VU1d6meg==,type:str]
    scopes: ENC[AES256_GCM,data:0Xn2lg93WgeLiturnTcSBoq5WIggtpxtfF1a,iv:yRO+BTmvP72BubrjiSXji7ECc5auU1dkmZrTQMZ3JfQ=,tag:7YBgxUHTWJzaCQzvaPKY2g==,type:str]
sops:
    age:
        - recipient: age1hruxjkg7m9sgjwlf6xvz74cy8l8g8ye0p800uja87w6fhz5qs5yqa2y6xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dEhmVStnTjFwK1plcWRk
            Mmc1K01BWG1EQzhuSkNzZDdPZ1IzZGRsTkZVClMzY1E3VTg0dW13bjBtbFFZRUJF
            MnZyY1N6QmUrdC9wT3FVeHRZN3dPY2cKLS0tIDlSWXBLS1IxQ3ZNOC9yZ2hLcTFz
            eWJPZzkvdndtZkxjeCtiNVdIS0RiSVEKQ6/ORWzytWq5ESr1TaEhAuik+CSGh18e
            O4DC4cdsx1BBxMy6LN+SmA5fkM3/mZT4Vs2k9WPl8JckE9mUuhk0jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T21:29:42Z"
    mac: ENC[AES256_GCM,data:UNGUAcTYs2UW4GJH4EfW5+qf11N3oolo2BgKpcVX8uj15Xh6vJnZ2AJcCGFeb0YNNxBUofLZzPtOsypOWAUXaUd6DjWzBp32dXeLhuZ1ouwCCttxIhWfAskEjAZEpUNHz3WYKgJBeQ0+9vpKfT2a8X+lNpU7xbpG3mn+VSWjj6I=,iv:Ne3KsKATqQajW8u4CAlTSKbtZdAlwthmHbAJcuB1GRQ=,tag:1Tg8xXEimaw5cNyingE5mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
