apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: kube-system
type: Opaque
stringData:
    clientID: ENC[AES256_GCM,data:hjOhdS8h46iQrMLvklW3MFkMIPE=,iv:OHKkIgHQnIEqU8zVeow4T9I+ZCqHVeJze/URyPoazO0=,tag:skk9SIKGy1c7lN3StjnzOw==,type:str]
    clientSecret: ENC[AES256_GCM,data:kyUFc1zOFU73kiZQ9xKR3kMipr5a0S5v20TWQ8KN0q6Wqj6Cql8bmmz2HPhaP/PgLs9I+MAcpz3Eox+YiFITcA==,iv:xIkqruPCCucDNcF4S3vn5jUgfbiCtLpKutMBAj+NLBM=,tag:9C6dyxBx3AXdfqQmtZz+NQ==,type:str]
    issuerURL: ENC[AES256_GCM,data:GRBmWIJwVpEvDLQgLVtLISsdy74ZZwzmscKG24h3CpowZxxItI2knds+fx7H0QctVYE=,iv:INRgfporDf1lSHvMDMIWAReKzf+8BUgeGYoPNtz/jdM=,tag:FGWaSBvxe9uJDwrMGlMMYA==,type:str]
    scopes: ENC[AES256_GCM,data:vEyr+Ky9EMhfKiFQ/HI5XaHlRjs=,iv:df2B2hSa91YOfOuq2jxwNxJfxIjQLBwBslk2Oa6hpcc=,tag:sn9jl72cfA53Vi7Avh3UOw==,type:str]
sops:
    age:
        - recipient: age1hruxjkg7m9sgjwlf6xvz74cy8l8g8ye0p800uja87w6fhz5qs5yqa2y6xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dEhmVStnTjFwK1plcWRk
            Mmc1K01BWG1EQzhuSkNzZDdPZ1IzZGRsTkZVClMzY1E3VTg0dW13bjBtbFFZRUJF
            MnZyY1N6QmUrdC9wT3FVeHRZN3dPY2cKLS0tIDlSWXBLS1IxQ3ZNOC9yZ2hLcTFz
            eWJPZzkvdndtZkxjeCtiNVdIS0RiSVEKQ6/ORWzytWq5ESr1TaEhAuik+CSGh18e
            O4DC4cdsx1BBxMy6LN+SmA5fkM3/mZT4Vs2k9WPl8JckE9mUuhk0jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T10:59:45Z"
    mac: ENC[AES256_GCM,data:FZ5LgS+15T3Z3xq1o9HowuEuMkUORRU4MXf6eACj96BRAdHrtAaLM1pUEXFSRJiA1Aq6oVqO7werH7JiD1rzt5ooWubNFxP4OdPY+Ur7+0Hh8sArcLdOdYS/diqVSWH8QReFO0fls6fejtrInRZMmaRq0QFKEQDjpROlfa8qDeA=,iv:A5mPWNfpHHYlZp+jgf0L8MCy20x+UkjTRwkeHFI5/sk=,tag:lIj+rao+FSGQCFEuoTAhXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
