apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana-admin-credentials.yaml
- postgres-credentials.yaml
- headlamp-token.yaml
- headlamp-oidc-kube-system.yaml
- headlamp-oidc-flux-system.yaml
- pgadmin-credentials.yaml
- n8n-credentials.yaml
- immich-credentials.yaml
- mcp-slack-bot-credentials.yaml
