apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: apps
spec:
  releaseName: open-webui
  interval: 5m
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: apps
      version: 8.22.1
  values:
    nodeSelector:
      kubernetes.io/hostname: k3s-worker3
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k3s-worker3
    persistence:
      enabled: true
      size: 50Gi
      accessModes:
        - ReadWriteOnce
      storageClass: local-path

    ollama:
      enabled: true
      fullnameOverride: "open-webui-ollama"
      runtimeClassName: nvidia
      gpu:
        enabled: true
        type: 'nvidia'
        number: 1
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
      nodeSelector:
        kubernetes.io/hostname: k3s-worker3
      persistence:
        enabled: true
        size: 30Gi
        storageClass: local-path
