apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: apps
spec:
  releaseName: open-webui
  interval: 5m
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: apps
      version: 8.10.0
  values:
    nodeSelector:
      kubernetes.io/hostname: k3s-worker3
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k3s-worker3
    persistence:
      enabled: true
      size: 50Gi
      accessModes:
        - ReadWriteOnce
      storageClass: local-path
