apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
