---
- name: Configure passwordless sudo for a user
  hosts: ubuntu_nodes
  become: true
  gather_facts: false

  vars:
    user_to_configure: "yuandrk"              # or pass via -e
    public_key_file: "../ssh_keys/id_rsa.pub"  # or an absolute path

  tasks:
    - name: Ensure the user exists in the sudo group
      user:
        name: "{{ user_to_configure }}"
        groups: "sudo"
        append: true

    - name: Configure passwordless sudo
      lineinfile:
        path: "/etc/sudoers.d/{{ user_to_configure }}"
        line: "{{ user_to_configure }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
        validate: "visudo -cf %s"

    - name: Install user SSH key
      authorized_key:
        user: "{{ user_to_configure }}"
        state: present
        key: "{{ lookup('file', public_key_file) }}"
