apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model-cache
  namespace: apps
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
