apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: infra
spec:
  chart:
    spec:
      chart: metallb
      version: "0.14.9"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: infra
  interval: 5m

