apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:g6YTAgRu0w==,iv:LXc94RKIpVDVxIbZt59iulZF6a8XWYv7jEUstvIj+/A=,tag:mV+3P65bwGwLwHxJaEQFug==,type:str]
    password: ENC[AES256_GCM,data:hxDmpG8OAIj4YPVYxRzSEMMYR3HjCxoTxjoBG/qj,iv:nkEivxQRoDGlTwMrkeCVCFIsE8G2ZSK1m/Y6aF205WA=,tag:zNykUZfLPJwdchZyHmO9aw==,type:str]
    database: ENC[AES256_GCM,data:ihjyXBPVQw==,iv:neOphWtMyxbe94K9khCaO1Er3Lp8o5XMLdOtZq3hJl4=,tag:z3Q/06sW4CtKmpK5Wko2+g==,type:str]
    host: ENC[AES256_GCM,data:ZKvPiilC8/c/,iv:iVvZqjJbq12aBSguzyP2MejBQcGVLJPVthT1TBHd/30=,tag:EI08QqHMm0JKOQQj0QZvSg==,type:str]
    port: ENC[AES256_GCM,data:T+lKcQ==,iv:7N/ULUIRlL3gbrPNgHWocvh+4FYMrGXlZbeZmMDr/Yo=,tag:mOKT3hz5AFuE2stYDlakCA==,type:str]
    url: ENC[AES256_GCM,data:UmjIkhuN2JkMzdLOtSKV/ldHwGAvrtxRKpGJx18o3LVY7UeqvfzOpKvVObc3r+F+Lcgax+LTYK6DszglIxNlRAJyV9y+wUIMDM4=,iv:tLcg7yZKy+oLWehZsdHgeoEyVbjtbc8WhA7W6IcCBMU=,tag:Kv2BuvyYzlm39dovjchQUg==,type:str]
sops:
    age:
        - recipient: age1hruxjkg7m9sgjwlf6xvz74cy8l8g8ye0p800uja87w6fhz5qs5yqa2y6xc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0STNITmVtVHpWZ3J5MWNZ
            N0lHaXJTb0VqL3FLNEM3dUVteFNEZWNFSGdJClRaWjArS05maXM0OEQ4YW9RMXRF
            RDFKcStud3RsVjhHbEkrSlRsVXViWW8KLS0tIGZhTFFLZGFIRjA5bkhacWpvVlFw
            T2FiRkxUME42RW9ZS2d6aFhsbGRWNlkKE0Y+2GpEoIxZsWx1GXHwHhrBPUCq85lO
            7tOmTAIxm74HeHs0mOIx14Nvc52k4giOfa/4WZJTBy0rhrXtDJxpsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T18:04:14Z"
    mac: ENC[AES256_GCM,data:PQQHAJYbDdlBLFnAifiA6hfsjEJqYyWpIi5AsaHSGRBz6n4gjt31j0jrgRop0u7BMoiK7Uq1v7AAKLTNbTZ6VJzD97WD1k9KlOVlsIUxZCjfyx4S0c8XbvWso5X0ip0DTcLtFQTLsUyvlI08m5fKi0KouFeWvFMEtqHzeqK1v+w=,iv:9nWwW7VQ0U9tToxmDRJSXuoxyj3adMt0l7tdftmPKqE=,tag:/ufkOX42sbYsAnbw/wHkNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
