apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: infra
spec:
  url: https://actions-runner-controller.github.io/actions-runner-controller