apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: infra
spec:
  interval: 10m
  releaseName: actions-runner-controller
  chart:
    spec:
      chart: actions-runner-controller
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: infra
      version: 0.25.0
  values:
    syncPeriod: 10m
    githubTokenSecret:
      name: github-token
      key: token