apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: apps
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: ">=0.10.0"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: apps
  values:
    # Shared configuration for all components
    controllers:
      main:
        containers:
          main:
            envFrom:
              - secretRef:
                  name: immich-credentials

    # Library storage
    immich:
      persistence:
        library:
          existingClaim: immich-library

    # Valkey (Redis replacement)
    valkey:
      enabled: true
      controllers:
        main:
          pod:
            nodeSelector:
              kubernetes.io/hostname: k3s-worker3
          containers:
            main:
              image:
                repository: docker.io/valkey/valkey
                tag: 9.0-alpine
      persistence:
        data:
          enabled: true
          size: 1Gi
          type: emptyDir

    # Server component
    server:
      enabled: true
      controllers:
        main:
          pod:
            nodeSelector:
              kubernetes.io/hostname: k3s-worker3
          containers:
            main:
              envFrom:
                - secretRef:
                    name: immich-credentials
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                limits:
                  memory: 2Gi

    # Machine learning component (CPU-only, GPU used by ollama)
    machine-learning:
      enabled: true
      controllers:
        main:
          pod:
            nodeSelector:
              kubernetes.io/hostname: k3s-worker3
          containers:
            main:
              resources:
                requests:
                  cpu: 500m
                  memory: 2Gi
                limits:
                  memory: 6Gi
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          storageClass: local-path
