apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: apps
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: ">=0.10.0"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: apps
  values:
    # Shared configuration for all components
    controllers:
      main:
        containers:
          main:
            envFrom:
              - secretRef:
                  name: immich-credentials

    # Library storage
    immich:
      persistence:
        library:
          existingClaim: immich-library

    # Valkey (Redis replacement)
    valkey:
      enabled: true
      controllers:
        main:
          pod:
            nodeSelector:
              kubernetes.io/hostname: k3s-worker3
          containers:
            main:
              image:
                repository: docker.io/valkey/valkey
                tag: 9.0-alpine
      persistence:
        data:
          enabled: true
          size: 1Gi
          type: emptyDir

    # Server component
    server:
      enabled: true
      controllers:
        main:
          pod:
            nodeSelector:
              kubernetes.io/hostname: k3s-worker3
            # Grant access to Intel iGPU for QSV hardware transcoding
            securityContext:
              supplementalGroups:
                - 44    # video group
                - 993   # render group (host GID for /dev/dri/renderD128)
          containers:
            main:
              envFrom:
                - secretRef:
                    name: immich-credentials
              # Enable privileged mode for GPU device access (Intel QSV)
              securityContext:
                privileged: true
              resources:
                requests:
                  cpu: 500m
                  memory: 4Gi
                limits:
                  memory: 8Gi
              probes:
                startup:
                  enabled: true
                  spec:
                    failureThreshold: 60
                    periodSeconds: 10
      # Mount Intel iGPU device for QSV transcoding
      persistence:
        dri:
          enabled: true
          type: hostPath
          hostPath: /dev/dri
          globalMounts:
            - path: /dev/dri

    # Machine learning component (CPU-only, GPU used by ollama)
    machine-learning:
      enabled: true
      controllers:
        main:
          pod:
            nodeSelector:
              kubernetes.io/hostname: k3s-worker3
          containers:
            main:
              resources:
                requests:
                  cpu: 500m
                  memory: 2Gi
                limits:
                  memory: 6Gi
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          storageClass: local-path
