apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: apps
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: ">=0.7.0"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: apps
  values:
    # Immich server component
    immich:
      persistence:
        library:
          existingClaim: immich-library

    # Server component (main API and web interface)
    server:
      enabled: true
      nodeSelector:
        kubernetes.io/hostname: k3s-worker3
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 2Gi

    # Machine learning component (with GPU)
    machine-learning:
      enabled: true
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: k3s-worker3
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          memory: 4Gi
          nvidia.com/gpu: 1
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"

    # Redis (in-memory, no persistent storage needed)
    redis:
      enabled: true
      architecture: standalone
      master:
        nodeSelector:
          kubernetes.io/hostname: k3s-worker3
        persistence:
          enabled: false
      replica:
        replicaCount: 0

    # PostgreSQL (MUST use local storage, not NFS)
    postgresql:
      enabled: true
      primary:
        nodeSelector:
          kubernetes.io/hostname: k3s-worker3
        persistence:
          enabled: true
          size: 20Gi
          storageClass: local-path
