apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-immich
  resources:
    requests:
      storage: 500Gi
