---
- name: Retrieve and display k3s token from master
  hosts: master
  become: yes
  gather_facts: false

  tasks:
    - name: Slurp k3s node-token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_file

    - name: Set k3s_token fact
      set_fact:
        k3s_token: "{{ k3s_token_file.content | b64decode }}"

    - name: Debug - print the k3s token
      debug:
        msg: "k3s token is: {{ k3s_token }}"
