apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: headlamp
      version: ">=0.21.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  targetNamespace: kube-system
  values:
    image:
      tag: "v0.26.0"
    
    # Service configuration
    service:
      type: ClusterIP
      port: 80
    
    # Ingress configuration
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - host: headlamp.yuandrk.net
          paths:
            - path: /
              pathType: Prefix
    
    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Enable plugins
    config:
      pluginsDir: "/headlamp/plugins"
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 100
      runAsGroup: 101