apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: yurii.andriuk@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          route53:
            region: eu-west-2
            accessKeyID: AKIA3AMRFZS6O4PIS2IA
            hostedZoneID: Z00590051L9DQ0G85AMA6
            secretAccessKeySecretRef:
              name: route53-secret
              key: secret-access-key