apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: apps
spec:
  interval: 10m
  chart:
    spec:
      chart: actualbudget
      version: 1.1.5
      sourceRef:
        kind: HelmRepository
        name: actualbudget
        namespace: apps
  values:
