apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/prod/monitoring/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age