apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-all
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/prod/monitoring
  prune: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: kube-prometheus-stack-operator
    namespace: monitoring
  - apiVersion: apps/v1
    kind: Deployment
    name: kube-prometheus-stack-grafana
    namespace: monitoring
