apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actualbudget
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/actualbudget/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: apps